#include "bit_tools.h"
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[])
{
  BitReader reader = open_bit_reader("compressed.bits");
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  printf("Current Byte: %x\n", reader.current_byte);
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d", read_bit(&reader));
  printf("%d\n", read_bit(&reader));
  close_bit_reader(&reader);
  return EXIT_SUCCESS;
}