name: Autograder run
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t a4grade .

    - name: Run tests using Docker image
      run: |
        docker run --rm -v code:./submission -v ./results:./results a4grade ./run_autograder > ./results/container.log 2>&1
        
    - name: Upload logs
      uses: actions/upload-artifact@v3
      with:
        name: container-logs
        path: ./results/container.log
